# Generated by Django 5.2.9 on 2025-12-29 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('POLICIA', 'Polícia'), ('BOMBEIROS', 'Bombeiros'), ('INEM', 'INEM'), ('PROTECAO_CIVIL', 'Proteção Civil')], max_length=30)),
                ('estado', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_CURSO', 'Em curso'), ('RESOLVIDA', 'Resolvida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distrito', models.CharField(choices=[('Aveiro', 'Aveiro'), ('Beja', 'Beja'), ('Braga', 'Braga'), ('Bragança', 'Bragança'), ('Castelo Branco', 'Castelo Branco'), ('Coimbra', 'Coimbra'), ('Évora', 'Évora'), ('Faro', 'Faro'), ('Guarda', 'Guarda'), ('Leiria', 'Leiria'), ('Lisboa', 'Lisboa'), ('Portalegre', 'Portalegre'), ('Porto', 'Porto'), ('Santarém', 'Santarém'), ('Setúbal', 'Setúbal'), ('Viana do Castelo', 'Viana do Castelo'), ('Vila Real', 'Vila Real'), ('Viseu', 'Viseu'), ('Açores', 'Açores'), ('Madeira', 'Madeira')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operadores', models.ManyToManyField(blank=True, related_name='incidentes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
